services:
  postgres:
    container_name: b2x-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: b2x-admin
      POSTGRES_PASSWORD: b2x-password
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local
